### ISSUE TITLE
Viash 0.7.4 breaks the pipeline

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/civ6_pipeline#8]
With Viash v0.7.3 (branch [state_mgmt](https://github.com/viash-io/civ6_pipeline/tree/state_mgmt), see  7f1b687500ea1c481477599917933d6db4cdae96), the following works:

```bash
export NXF_CONTAINER_ENTRYPOINT_OVERRIDE=true
nextflow run workflows/civ6_pipeline/main.nf \
  --input data/AutoSave_0158.Civ6Save \
  --id test \
  --publish_dir out/ \
  -with-docker
```

Without the `NXF_CONTAINER_ENTRYPOINT_OVERRIDE=true`, with a recent version of Nextflow the following error occurs because the base container for `convert_plot` has an `ENTRYPOINT` specified:

```bash
Command error:
  convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
  convert: unrecognized option `-c' @ error/convert.c/ConvertImageCommand/1244.
```

With Viash v0.7.4, it's possible to override the `ENTRYPOINT` in the Viash component config:

```yaml
...
platforms:
  - type: docker
    image: dpokidov/imagemagick:7.1.0-50
    entrypoint: /bin/bash
    setup:
      - type: apt
        packages: [ "procps" ]
```

Updating the value of Viash in `_viash.yaml` and running `viash ns build --setup cb`, the following happens when the pipeline is started as above:

```bash
N E X T F L O W  ~  version 22.10.7
Launching `workflows/civ6_pipeline/main.nf` [agitated_mirzakhani] DSL2 - revision: 12a2ac4b0e
executor >  local (4)
[98/288049] process > run_wf_2:parse_header:parse_header_process (1) [100%] 1 of 1 ✔
[09/008521] process > run_wf_2:parse_map:parse_map_process (1)       [100%] 1 of 1 ✔
[69/bee6e2] process > run_wf_2:plot_map:plot_map_process (1)         [100%] 1 of 1 ✔
[ef/47e045] process > run_wf_2:convert_plot:convert_plot_process (1) [100%] 1 of 1 ✔
[-        ] process > run_wf_2:combine_plots:combine_plots_process   -
[test, [input:.../civ6_save_renderer/data/AutoSave_0158.Civ6Save]]
Error in module 'convert_plot' id 'test' argument 'output'.
  Required output file is missing. Expression: par.required
```

**Comment by tverbeiren** [comment]
Nextflow does not cope well with the `ENTRYPOINT` setting, whatever value it has. Therefore, Viash [overrides its value](http://viash.io/reference/config/platforms/docker/#entrypoint) by default to set it to `[]`.

However, it does not stop there because the container still has to run _something_ at startup and that's where we can set the `CMD` entry from the Viash config:

```yaml
platforms:
  - type: docker
    image: dpokidov/imagemagick:7.1.0-50
    cmd: /bin/bash
    setup:
      - type: apt
        packages: [ "procps" ]
```

__Please note__: If you want to remove the `ENTRYPOINT []` from the override, you can set `entrypoint: null` in the config file.
